# Generated by Django 4.1.5 on 2024-02-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0003_watchlist_platform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="streamplatform",
            old_name="url",
            new_name="website",
        ),
    ]
